#!/bin/bash

echo "Enter the YEAR"

read YEAR

if [[ $YEAR =~ ^[[:digit:]]+$ ]];
then 
	Y=$(( $YEAR % 4 ))
	if [ $Y -eq 0 ];
	then
	echo "$YEAR is a leap year"
	else 
	echo "$YEAR is not a leap Year"
	fi

else
	echo "Enter only numbers"
fi
